# This version of config.mk was generated by:
# ./configure CC=cc
# Any changes made here will be lost if configure is re-run
bindir = /usr/local/bin
datadir = /usr/local/share
datarootdir = /usr/local/share
docdir = /usr/local/share/doc/riot
dvidir = /usr/local/share/doc/riot
exec_prefix = /usr/local
htmldir = /usr/local/share/doc/riot
includedir = /usr/local/include
infodir = /usr/local/share/info
libdir = /usr/local/lib
libexecdir = /usr/local/libexec
localedir = /usr/local/share/locale
localstatedir = /usr/local/var
mandir = /usr/local/share/man
pdfdir = /usr/local/share/doc/riot
prefix = /usr/local
psdir = /usr/local/share/doc/riot
sbindir = /usr/local/sbin
sharedstatedir = /usr/local/com
srcdir = .
sysconfdir = /usr/local/etc
