'\" t
.\"     Title: praxis
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-07-08
.\"    Manual: Mutineer's Guide - praxis
.\"    Source: Mutiny
.\"  Language: English
.\"
.TH "PRAXIS" "7" "2020-07-08" "Mutiny" "Mutineer\(aqs Guide \- praxis"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
praxis \- package manager for Mutiny\(aqs package API, theory
.SH "SYNOPSIS"
.sp
This page consists of documentation and other notes on the design of the \fBpraxis\fP package manager.
.SH "PHILOSOPHY"
.sp
Starting from the bottom\-up, \fBpraxis\fP aims to be composed of multiple small utilities that do one
thing, so as to ease frontend development and more importantly, to make the surface area for issues
very small. With this design in mind, \fBpraxis\fP can be fast and very compact, while providing a lot
of useful functionality for developers, metadata consumers, and users.
.sp
No code evaluation is used, up until the actual building of packages.
All code is generated purely by following hierarchies of inheritance for actions and metadata.
.sp
Concepts like \c
.URL "https://skarnet.org/software/s6/s6\-envdir.html" "envdirs" " "
are used to additionally ease
the amount of parsing that must be done to files in order to construct metadata for packages,
repositories, and libraries.
.sp
Furthermore, another goal is ensuring that it should be possible to get metadata from packages
without having to call out to a shell running arbitrary code or duplicate metadata. This has tended
to be a problem for other source\-based package formats, such as the Arch Linux AUR, Exherbo\(cqs
exheres\-0, and Gentoo\(cqs EAPI. That is to say, it should be relatively static and not actually
require a shell parser for anything other than running the actual actions that build a package.
.SH "DEPENDENCIES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
A POSIX\-compliant shell: on Mutiny this is \c
.URL "https://github.com/ibara/oksh" "oksh(1)" ","
but it is
written with intent that anything vaguely POSIX compliant should function properly.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
.URL "https://git.mutiny.red/mutiny/idioms" "\f(CRidioms\fP" ""
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Used in lieu of implementing a bunch of small flow functions into the package API.
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
.URL "https://skarnet.org/software/s6\-portable\-utils" "\f(CRs6\-portable\-utils\fP" ""
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRs6\-update\-symlinks\fP is used for updating repositories while respecting priority.
.RE
.RE
.SH "ROADMAP"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Build repository management utilities
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRrepo\-list\fP \- list all repositories by if they have libraries and/or packages.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRrepo\-update\fP \- update repositories and combine them according to priority.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests (currently are skipped until things settle)
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRrepo\-lint\fP \- lint repositories and check their validity according to theory(5).
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests
.RE
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Build theory utilities
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRtheory\-construct\-action\fP \- resolve and print all action (build script) parts of a
theory.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRtheory\-construct\-metadata\fP \- resolve and print all metadata parts of a theory.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Open questions:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Should packages be created by concatenation of things, which creates a mostly
self\-contained and perhaps easier\-debugged build script, or should they be parsed more
heavily by the package manager itself? This needs to be decided pretty soon since it
basically dictates the rest of the format.
.RE
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Build package building utilities
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRpkg\-gen\fP \- create a self\-contained package script.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
See the first open question above to understand my anxieties with this format.
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRpkg\-build\fP \- run each phase of a package script
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Tests
.RE
.RE
.RE
.SH "WISHLIST"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Multiple repositories
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Intra\-repository dependencies
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Priority levels
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CR::primary\fP is the most important repository.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Other repositories should always be able to depend on libraries in repositories that
are have a higher priority.
.RE
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Repository synchronization
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Use \fBgit\fP for synchronization by default, but allow alternative transport/sync methods.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Paludis has sync prefixes: \f(CRcave sync \-s local repository\fP, which are really useful for
fast development of repositories and packages within them.
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Something akin to \f(CRapt\-get source\fP would be pretty nice \- we have all the metadata to do just
this anyway, since all packages are built from source.
.RE
.SS "Example configuration"
.sp
Here\(cqs what I\(cqm imagining for the configuration format. Basically, something akin to Paludis\(aq
configuration format, but simpler.
.SS "\fI/etc/praxis/options.conf\fP"
.sp
Options enabled on packages.
.sp
.if n .RS 4
.nf
*           \-* ruby ssl
tz          leaps
toybox      static
nginx       webdav pcre
.fi
.if n .RE
.sp
Files may also be put in \fI/etc/praxis/options.d/*.conf\fP, and they\(cqll take priority over
\fIoptions.conf\fP.
.SS "\fI/etc/praxis/world\fP"
.sp
Packages explicitly requested to be installed by the user. They were not installed as dependencies
of other packages.
.sp
.if n .RS 4
.nf
beets
lighttpd
mpd
passage
.fi
.if n .RE
.SH "ETYMOLOGY"
.sp
Named as such to conform with the rest of the Mutiny naming scheme. "Praxis," the word, means in the
original Greek, "action." Packages are referred to as theories, thus praxis carries out a
theory(3). \f(CRpraxis\fP is the reference implementation of the package manager used by mutiny(7).
.SH "SEE ALSO"
.sp
theory(5)
.SH "CONTRIBUTING"
.sp
The canonical URL of this repository is \c
.URL "https://git.mutiny.red/mutiny/praxis" "" "."
Submit patches and bugs to <\c
.MTO "kylie\(atsomas.is" "" ">."
.sp
There is also an IRC channel for \fBpraxis\fP and other projects at \c
.URL "irc://irc.freenode.net/#mutiny" "" "."
Please don\(cqt hesitate to message if you need help.
.SH "LICENSE"
.sp
\fBpraxis\fP is in the public domain.
.sp
To the extent possible under law, Kylie McClain <\c
.MTO "kylie\(atsomas.is" "" ">"
has waived all copyright and
related or neighboring rights to this work.
.sp
.URL "http://creativecommons.org/publicdomain/zero/1.0/" "" ""