#!/bin/sh

praxis_lib_dir=~/git/mutiny/praxis/lib
praxis_exec_dir=~/git/mutiny/praxis/libexec
praxis_repo_dir=~/git/mutiny/praxis-repos

for f in "${praxis_lib_dir}"/*;do
    . "${f}"
done

praxis_command="${1:-help}"; shift

cleanenv

. "${praxis_exec_dir}"/praxis-"${praxis_command}" "$@"
