= praxis(7)

== Name

praxis - a package manager for Mutiny's package API, theory

== Philosophy

Starting from the bottom-up, `praxis` aims to be composed of multiple small utilities that do one
thing, so as to ease frontend development and more importantly, to make the surface area for issues
very small. With this design in mind, `praxis` can be fast and very compact, while providing a lot
of useful functionality for developers, metadata consumers, and users.

No code evaluation is used at any point. All code is generated purely by following hierarchies of
inheritance for actions (build scripts) and metadata.
Concepts like https://skarnet.org/software/s6/s6-envdir.html[envdirs] are used to additionally ease
the amount of parsing that must be done to files in order to construct metadata for packages,
repositories, and libraries.

Furthermore, another goal is ensuring that it should be possible to get metadata from packages
without having to call out to a shell running arbitrary code or duplicate metadata. This has tended
to be a problem for other source-based package formats, such as the Arch Linux AUR, Exherbo's
exheres-0, and Gentoo's EAPI.

include::footer.adoc[]
