= praxis(7)

:url-skarnet: https://skarnet.org/software

== Name

praxis - package manager for Mutiny's package API, theory

== Synopsis

This page consists of documentation and other notes on the design of the *praxis* package manager.

== Philosophy

Starting from the bottom-up, *praxis* aims to be composed of multiple small utilities that do one
thing, so as to ease frontend development and more importantly, to make the surface area for issues
very small. With this design in mind, *praxis* can be fast and very compact, while providing a lot
of useful functionality for developers, metadata consumers, and users.

No code evaluation is used at any point. All code is generated purely by following hierarchies of
inheritance for actions (build scripts) and metadata.
Concepts like {url-skarnet}/s6/s6-envdir.html[envdirs] are used to additionally ease
the amount of parsing that must be done to files in order to construct metadata for packages,
repositories, and libraries.

Furthermore, another goal is ensuring that it should be possible to get metadata from packages
without having to call out to a shell running arbitrary code or duplicate metadata. This has tended
to be a problem for other source-based package formats, such as the Arch Linux AUR, Exherbo's
exheres-0, and Gentoo's EAPI. That is to say, it should be relatively static and not actually
require a shell parser for anything other than running the actual actions that build a package.

== Dependencies

* https://git.mutiny.red/mutiny/idioms[`idioms`]
* A POSIX-compliant shell
* {url-skarnet}/s6-portable-utils[`s6-portable-utils`]
    ** `s6-update-symlinks` is used for updating repositories while respecting priority.

== Roadmap

* [ ] Build repository management utilities
    ** [x] `repo-list` - list all repositories by if they have libraries and/or packages.
        *** [x] Tests
    ** [x] `repo-update` - update repositories and combine them according to priority.
        *** [ ] Tests (currently are skipped until things settle)
    ** [ ] `repo-lint` - lint repositories and check their validity according to theory(5).
        *** [ ] Tests

* [ ] Build theory construction utilities
    ** [x] `theory-action` - resolve and print all action (build script) parts of a theory.
        *** [ ] Tests
    ** [x] `theory-metadata` - resolve and print all metadata parts of a theory.
        *** [ ] Tests
    ** Open questions:
        . Should packages be created by concatenation of things, which creates a mostly
          self-contained and perhaps easier-debugged build script, or should they be parsed more
          heavily by the package manager itself? This needs to be decided pretty soon since it
          basically dictates the rest of the format.

* [ ] Build package building utilities
    ** [x] `pkg-gen` - create a self-contained package script.
        *** [ ] Tests
        *** See the first open question above to understand my anxieties with this format.

== Wishlist

* Multiple repositories
    ** Intra-repository dependencies
    ** Priority levels
        *** `::primary` is the most important repository.
        *** Other repositories should always be able to depend on libraries in repositories that
            are have a higher priority.

* Repository synchronization
    ** Use *git* for synchronization by default, but allow alternative transport/sync methods.
    ** Paludis has sync prefixes: `cave sync -s local repository`, which are really useful for
    fast development of repositories and packages within them.

* Something akin to `apt-get source` would be pretty nice - we have all the metadata to do just
  this anyway, since all packages are built from source.

=== Example configuration

Here's what I'm imagining for the configuration format. Basically, something akin to Paludis'
configuration format, but simpler.

==== _/etc/praxis/options.conf_

Options enabled on packages.

[example]
----
*           -* ruby ssl
tz          leaps
toybox      static
nginx       webdav pcre
----

Files may also be put in _/etc/praxis/options.d/*.conf_, and they'll take priority over
_options.conf_.

==== _/etc/praxis/world_

Packages explicitly requested to be installed by the user. They were not installed as dependencies
of other packages.

[example]
----
beets
lighttpd
mpd
passage
----

[glossary]
== Glossary

[glossary]
actions::
    The actual executable code used to build a package.

theory::
    . The package API. See theory(5).

    . A directory containing the data used to build a package. A directory contains a package if it
      has either an action, or a library (which creates actions).

== Etymology

Named as such to conform with the rest of the Mutiny naming scheme. "Praxis," the word, means in the
original Greek, "action." Packages are referred to as theories, thus praxis carries out a
theory(3). `praxis` is the reference implementation of the package manager used by mutiny(7).

== See also

<<theory.5.adoc#,theory(5)>>

include::footer.adoc[]
